version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./src/hotel_reservation:/app/src/hotel_reservation
      - flask_migrations:/app/src/hotel_reservation/migrations
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: hotel_reservation_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  flask_migrations: